apiVersion: batch/v1
kind: CronJob
metadata:
    name: zerodaynewsletter-cronjob
spec:
    schedule: "0 3 * * *" # Run once a day at 3AM
    jobTemplate:
        spec:
            template:
                metadata:
                    labels:
                        app: zerodaynewsletter
                spec:
                    containers:
                    - name: zerodaynewsletter
                      image: localhost:32000/zerodaynewsletter:v1
                      command: ["python", "zerodaynewsletter.py"]
                      env:
                      - name: SLACK_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: zerodaynewsletter-secrets
                                key: SLACK_API_KEY
                      - name: CHANNEL_ID
                        valueFrom:
                            secretKeyRef:
                                name: zerodaynewsletter-secrets
                                key: CHANNEL_ID
                      - name: IMAGE_URL
                        valueFrom:
                            secretKeyRef:
                                name: zerodaynewsletter-secrets
                                key: IMAGE_URL
                    restartPolicy: OnFailure




